repos:
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/jendrikseipp/vulture
  rev: v2.14
  hooks:
    - id: vulture
      pass_filenames: false
      require_serial: true
      args: [--min-confidence=90, --exclude=__init__.py, agent/]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args: ["--branch", "main", "--branch", "develop"]
  - id: check-added-large-files
    args: ["--maxkb=1000"]
  - id: check-ast
  - id: check-json
  - id: check-toml