services:
  vision_agent:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: vision_agent_container
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - CREDENTIALS_PATH=/secrets/application_default_credentials.json
    volumes:
      - ./application_default_credentials.json:/secrets/application_default_credentials.json:ro
